Genome:
  - mm10
  - hg38

Window_kb:
  - 5
Bin_size:
  - 10

Threshold:
  n_reads: 1000
  f_mapped_reads: 0.5
  f_duplicates: 0.5
  n_peaks: 10
  n_exp_per_tf: 250

Normalization:
  size_factor: 100000

Track_hub:
  outfolder: "track_hub"
  outfiles:
    - "hub.txt"
    - "genomes.txt"
    - "ChIP_Atlas.html"
    - "url.txt"

Ensembl:
  GeneID_GeneName_Synonyms:
    mm10: mm10_ENSID_Genename_synonyms.txt.gz
    mm39: mm39_ENSID_Genename_synonyms.txt.gz
    hg19: hg19_ENSID_Genename_synonyms.txt.gz
    hg38: hg38_ENSID_Genename_synonyms.txt.gz
  GeneID_GeneName_Synonyms_dict:
    mm10: mm10_ENSID_Genename_synonyms.txt
    mm39: mm39_ENSID_Genename_synonyms.txt
    hg19: hg19_ENSID_Genename_synonyms.txt
    hg38: hg38_ENSID_Genename_synonyms.txt

Promoterome:
  mm10: /bigdata/jbreda/genome/mm10/mm10_promoters_v2.gff.gz
  mm39: /bigdata/jbreda/genome/mm39/mm39_promoters_v1.gff.gz
  hg19: /bigdata/jbreda/genome/hg19/hg19_promoters_v2.gff.gz
  hg38: /bigdata/jbreda/genome/hg38/hg38_promoters_v1.gff.gz

TF_Complex:
  mm10: resources/complex/MusMusculus.tsv
  hg38: resources/complex/HomoSapiens.tsv