Genome:
  - mm10
  - hg38

Version:
  - v3

Window_kb:
  - 5
Bin_size:
  - 10

Threshold:
  n_reads: 1000
  f_mapped_reads: 0.1
  f_duplicates: .95
  n_peaks: 1
  n_exp_per_tf: 128

Track_hub:
  outfolder: "track_hub"
  outfiles:
    - "hub.txt"
    - "genomes.txt"
    - "ChIP_Atlas.html"
    - "url.txt"

Ensembl:
  GeneID_GeneName_Synonyms:
    mm10: mm10_ENSID_Genename_synonyms.txt.gz
    mm39: mm39_ENSID_Genename_synonyms.txt.gz
    hg19: hg19_ENSID_Genename_synonyms.txt.gz
    hg38: hg38_ENSID_Genename_synonyms.txt.gz
  GeneID_GeneName_Synonyms_dict:
    mm10: mm10_ENSID_Genename_synonyms.txt
    mm39: mm39_ENSID_Genename_synonyms.txt
    hg19: hg19_ENSID_Genename_synonyms.txt
    hg38: hg38_ENSID_Genename_synonyms.txt

TF_Complex:
  mm10: resources/complex/MusMusculus.tsv
  hg38: resources/complex/HomoSapiens.tsv

Genome_fasta:
  mm10: genome/mm10/Mus_musculus.GRCm38.dna.primary_assembly.fa
  hg38: genome/hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
  
Chrom_size:
  mm10: genome/mm10/Mus_musculus.GRCm38.dna.primary_assembly.chrom.sizes
  hg38: genome/hg38/Homo_sapiens.GRCh38.dna.primary_assembly.chrom.sizes

PWM_threshold: 0.5

GO_list:
  - negative_regulation_of_transcription_by_RNA_polymerase_II
  - positive_regulation_of_transcription_by_RNA_polymerase_II
  - regulation_of_transcription_by_RNA_polymerase_II
  - transcription_cis-regulatory_region_binding

Curated_TF_list:
  mm10: resources/mouse_ensemble_tfs_from_lambertetal_isyes.unique.txt
  hg38: resources/The_Human_Transcription_Factors_Cell_2018.xlsx
